-- 현재 스키마의 역할과 사용 위치를 DB 메타데이터만으로 확인할 수 있도록 설명을 추가한다.
-- 기존 컬럼의 타입, NULL 허용 여부, 기본값, 키 정의는 변경하지 않는다.

ALTER TABLE conversations COMMENT = '사용자 대화 세션. Spring 채팅 기능에서 현재 사용.';
ALTER TABLE conversations MODIFY COLUMN id CHAR(36) NOT NULL COMMENT '대화 식별자.';
ALTER TABLE conversations MODIFY COLUMN location_id VARCHAR(32) NOT NULL COMMENT '추천 위치 식별자.';
ALTER TABLE conversations MODIFY COLUMN active BOOLEAN NOT NULL DEFAULT TRUE COMMENT '대화 활성 상태.';
ALTER TABLE conversations MODIFY COLUMN created_at DATETIME(6) NOT NULL COMMENT '대화 생성 시각.';
ALTER TABLE conversations MODIFY COLUMN updated_at DATETIME(6) NOT NULL COMMENT '대화 수정 시각.';
ALTER TABLE conversations MODIFY COLUMN deactivated_at DATETIME(6) NULL COMMENT '대화 비활성화 시각.';
ALTER TABLE conversations MODIFY COLUMN user_id CHAR(36) NULL COMMENT '대화를 소유한 users.id.';

ALTER TABLE chat_messages COMMENT = '대화에 포함된 사용자·시스템 메시지. Spring 채팅과 SSE 결과 저장에 사용.';
ALTER TABLE chat_messages MODIFY COLUMN id CHAR(36) NOT NULL COMMENT '메시지 식별자.';
ALTER TABLE chat_messages MODIFY COLUMN conversation_id CHAR(36) NOT NULL COMMENT '소속 conversations.id.';
ALTER TABLE chat_messages MODIFY COLUMN role VARCHAR(16) NOT NULL COMMENT '메시지 발화자 역할.';
ALTER TABLE chat_messages MODIFY COLUMN status VARCHAR(16) NOT NULL COMMENT '메시지 처리 상태.';
ALTER TABLE chat_messages MODIFY COLUMN content TEXT NOT NULL COMMENT '메시지 본문.';
ALTER TABLE chat_messages MODIFY COLUMN created_at DATETIME(6) NOT NULL COMMENT '메시지 생성 시각.';
ALTER TABLE chat_messages MODIFY COLUMN completed_at DATETIME(6) NULL COMMENT '메시지 처리 완료 시각.';

ALTER TABLE restaurants COMMENT = 'KOMSCO 원천 음식점과 추천용 기본 정보. Spring 추천과 Python Batch가 함께 사용.';
ALTER TABLE restaurants MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT COMMENT '내부 음식점 식별자.';
ALTER TABLE restaurants MODIFY COLUMN name VARCHAR(120) NOT NULL COMMENT '음식점 상호.';
ALTER TABLE restaurants MODIFY COLUMN category VARCHAR(40) NULL COMMENT '음식점 업종 또는 카테고리.';
ALTER TABLE restaurants MODIFY COLUMN representative_menu VARCHAR(120) NULL COMMENT '대표 메뉴 표시값.';
ALTER TABLE restaurants MODIFY COLUMN average_price INT NULL COMMENT '추천 필터에 사용하는 평균 가격.';
ALTER TABLE restaurants MODIFY COLUMN address VARCHAR(255) NOT NULL COMMENT '지번 또는 기본 주소.';
ALTER TABLE restaurants MODIFY COLUMN location_id VARCHAR(32) NULL COMMENT '서비스 위치 그룹 식별자.';
ALTER TABLE restaurants MODIFY COLUMN latitude DECIMAL(10, 7) NULL COMMENT '음식점 위도.';
ALTER TABLE restaurants MODIFY COLUMN longitude DECIMAL(10, 7) NULL COMMENT '음식점 경도.';
ALTER TABLE restaurants MODIFY COLUMN zero_pay_available BOOLEAN NOT NULL COMMENT 'ZeroPay 사용 가능 여부.';
ALTER TABLE restaurants MODIFY COLUMN sample_data BOOLEAN NOT NULL DEFAULT FALSE COMMENT '개발용 샘플 데이터 여부.';
ALTER TABLE restaurants MODIFY COLUMN active BOOLEAN NOT NULL DEFAULT TRUE COMMENT '원천 운영 상태.';
ALTER TABLE restaurants MODIFY COLUMN created_at DATETIME(6) NOT NULL COMMENT '레코드 생성 시각.';
ALTER TABLE restaurants MODIFY COLUMN updated_at DATETIME(6) NOT NULL COMMENT '레코드 수정 시각.';
ALTER TABLE restaurants MODIFY COLUMN recommendation_ready BOOLEAN NOT NULL DEFAULT TRUE COMMENT '추천 데이터 구축 완료 여부.';
ALTER TABLE restaurants MODIFY COLUMN external_merchant_id VARCHAR(255) NULL COMMENT 'KOMSCO 원천 가맹점 식별자.';
ALTER TABLE restaurants MODIFY COLUMN detail_address VARCHAR(255) NULL COMMENT '원천 상세 주소.';
ALTER TABLE restaurants MODIFY COLUMN postal_code VARCHAR(20) NULL COMMENT '우편번호.';
ALTER TABLE restaurants MODIFY COLUMN legal_dong_code VARCHAR(16) NULL COMMENT '법정동 코드.';
ALTER TABLE restaurants MODIFY COLUMN legal_dong_name VARCHAR(80) NULL COMMENT '법정동 이름.';
ALTER TABLE restaurants MODIFY COLUMN industry_code VARCHAR(20) NULL COMMENT '원천 업종 코드.';
ALTER TABLE restaurants MODIFY COLUMN industry_name VARCHAR(255) NULL COMMENT '원천 업종 이름.';
ALTER TABLE restaurants MODIFY COLUMN provider_institution_code VARCHAR(20) NULL COMMENT '원천 제공기관 코드.';
ALTER TABLE restaurants MODIFY COLUMN business_status_code VARCHAR(20) NULL COMMENT '원천 영업 상태 코드.';
ALTER TABLE restaurants MODIFY COLUMN business_status_name VARCHAR(80) NULL COMMENT '원천 영업 상태 이름.';
ALTER TABLE restaurants MODIFY COLUMN source_reference_date DATE NULL COMMENT '원천 기준일.';
ALTER TABLE restaurants MODIFY COLUMN source_provider VARCHAR(32) NULL COMMENT '원천 제공자 구분.';
ALTER TABLE restaurants MODIFY COLUMN last_synced_at DATETIME(6) NULL COMMENT '원천 동기화 시각.';
ALTER TABLE restaurants MODIFY COLUMN recommendation_eligibility VARCHAR(16) NOT NULL DEFAULT 'UNKNOWN' COMMENT '검증 결과에 따른 추천 가능 상태.';

ALTER TABLE restaurant_schedules COMMENT = '음식점 영업시간 묶음. Spring 도메인에서 현재 사용.';
ALTER TABLE restaurant_schedules MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT COMMENT '영업시간 묶음 식별자.';
ALTER TABLE restaurant_schedules MODIFY COLUMN restaurant_id BIGINT NOT NULL COMMENT '소속 restaurants.id.';
ALTER TABLE restaurant_schedules MODIFY COLUMN name VARCHAR(80) NOT NULL COMMENT '영업시간 묶음 이름.';
ALTER TABLE restaurant_operating_days COMMENT = '정기 영업 요일. Spring 추천 도메인에서 사용.';
ALTER TABLE restaurant_operating_days MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT COMMENT '영업 요일 식별자.';
ALTER TABLE restaurant_operating_days MODIFY COLUMN schedule_id BIGINT NOT NULL COMMENT '소속 restaurant_schedules.id.';
ALTER TABLE restaurant_operating_days MODIFY COLUMN day_of_week VARCHAR(16) NOT NULL COMMENT '요일 값.';
ALTER TABLE restaurant_operating_hours COMMENT = '정기 영업 시간. Spring 추천 도메인에서 사용.';
ALTER TABLE restaurant_operating_hours MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT COMMENT '영업 시간 식별자.';
ALTER TABLE restaurant_operating_hours MODIFY COLUMN schedule_id BIGINT NOT NULL COMMENT '소속 restaurant_schedules.id.';
ALTER TABLE restaurant_operating_hours MODIFY COLUMN opens_at TIME NOT NULL COMMENT '영업 시작 시각.';
ALTER TABLE restaurant_operating_hours MODIFY COLUMN closes_at TIME NOT NULL COMMENT '영업 종료 시각.';
ALTER TABLE restaurant_closed_days COMMENT = '정기 휴무 요일. Spring 추천 도메인에서 사용.';
ALTER TABLE restaurant_closed_days MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT COMMENT '휴무 요일 식별자.';
ALTER TABLE restaurant_closed_days MODIFY COLUMN restaurant_id BIGINT NOT NULL COMMENT '소속 restaurants.id.';
ALTER TABLE restaurant_closed_days MODIFY COLUMN day_of_week VARCHAR(16) NOT NULL COMMENT '휴무 요일 값.';
ALTER TABLE restaurant_closed_hours COMMENT = '영업 중 휴게 시간. Spring 추천 도메인에서 사용.';
ALTER TABLE restaurant_closed_hours MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT COMMENT '휴게 시간 식별자.';
ALTER TABLE restaurant_closed_hours MODIFY COLUMN schedule_id BIGINT NOT NULL COMMENT '소속 restaurant_schedules.id.';
ALTER TABLE restaurant_closed_hours MODIFY COLUMN starts_at TIME NOT NULL COMMENT '휴게 시작 시각.';
ALTER TABLE restaurant_closed_hours MODIFY COLUMN ends_at TIME NOT NULL COMMENT '휴게 종료 시각.';

ALTER TABLE message_recommendations COMMENT = '메시지별 추천 음식점 결과. Spring 추천 결과 저장에 현재 사용.';
ALTER TABLE message_recommendations MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT COMMENT '추천 결과 식별자.';
ALTER TABLE message_recommendations MODIFY COLUMN message_id CHAR(36) NOT NULL COMMENT '소속 chat_messages.id.';
ALTER TABLE message_recommendations MODIFY COLUMN restaurant_id BIGINT NOT NULL COMMENT '추천 restaurants.id.';
ALTER TABLE message_recommendations MODIFY COLUMN recommendation_rank INT NOT NULL COMMENT '추천 순위.';
ALTER TABLE message_recommendations MODIFY COLUMN reason VARCHAR(500) NOT NULL COMMENT '추천 사유.';

ALTER TABLE users COMMENT = '서비스 사용자 계정. Spring 인증과 사용자 기능에서 현재 사용.';
ALTER TABLE users MODIFY COLUMN id CHAR(36) NOT NULL COMMENT '사용자 식별자.';
ALTER TABLE users MODIFY COLUMN email VARCHAR(255) NOT NULL COMMENT '로그인 이메일.';
ALTER TABLE users MODIFY COLUMN display_name VARCHAR(100) NOT NULL COMMENT '표시 이름.';
ALTER TABLE users MODIFY COLUMN status VARCHAR(20) NOT NULL COMMENT '계정 상태.';
ALTER TABLE users MODIFY COLUMN role VARCHAR(20) NOT NULL COMMENT '권한 역할.';
ALTER TABLE users MODIFY COLUMN created_at DATETIME(6) NOT NULL COMMENT '계정 생성 시각.';
ALTER TABLE users MODIFY COLUMN updated_at DATETIME(6) NOT NULL COMMENT '계정 수정 시각.';
ALTER TABLE users MODIFY COLUMN last_login_at DATETIME(6) NULL COMMENT '마지막 로그인 시각.';
ALTER TABLE user_credentials COMMENT = '사용자 비밀번호와 로그인 잠금 정보. Spring 인증에서 현재 사용.';
ALTER TABLE user_credentials MODIFY COLUMN user_id CHAR(36) NOT NULL COMMENT '소속 users.id.';
ALTER TABLE user_credentials MODIFY COLUMN password_hash VARCHAR(255) NOT NULL COMMENT '해시된 비밀번호.';
ALTER TABLE user_credentials MODIFY COLUMN password_changed_at DATETIME(6) NULL COMMENT '비밀번호 변경 시각.';
ALTER TABLE user_credentials MODIFY COLUMN failed_login_count INT NOT NULL DEFAULT 0 COMMENT '연속 로그인 실패 횟수.';
ALTER TABLE user_credentials MODIFY COLUMN locked_until DATETIME(6) NULL COMMENT '계정 잠금 해제 시각.';
ALTER TABLE SPRING_SESSION COMMENT = 'Spring Session JDBC가 관리하는 HTTP 세션. 현재 런타임 사용.';
ALTER TABLE SPRING_SESSION MODIFY COLUMN PRIMARY_ID CHAR(36) NOT NULL COMMENT '세션 내부 기본 식별자.';
ALTER TABLE SPRING_SESSION MODIFY COLUMN SESSION_ID CHAR(36) NOT NULL COMMENT '외부 세션 식별자.';
ALTER TABLE SPRING_SESSION MODIFY COLUMN CREATION_TIME BIGINT NOT NULL COMMENT '세션 생성 epoch 시각.';
ALTER TABLE SPRING_SESSION MODIFY COLUMN LAST_ACCESS_TIME BIGINT NOT NULL COMMENT '마지막 접근 epoch 시각.';
ALTER TABLE SPRING_SESSION MODIFY COLUMN MAX_INACTIVE_INTERVAL INT NOT NULL COMMENT '최대 비활성 간격.';
ALTER TABLE SPRING_SESSION MODIFY COLUMN EXPIRY_TIME BIGINT NOT NULL COMMENT '세션 만료 epoch 시각.';
ALTER TABLE SPRING_SESSION MODIFY COLUMN PRINCIPAL_NAME VARCHAR(100) NULL COMMENT '인증 주체 이름.';
ALTER TABLE SPRING_SESSION_ATTRIBUTES COMMENT = 'Spring Session의 세션 속성. 현재 런타임 사용.';
ALTER TABLE SPRING_SESSION_ATTRIBUTES MODIFY COLUMN SESSION_PRIMARY_ID CHAR(36) NOT NULL COMMENT '소속 SPRING_SESSION.PRIMARY_ID.';
ALTER TABLE SPRING_SESSION_ATTRIBUTES MODIFY COLUMN ATTRIBUTE_NAME VARCHAR(200) NOT NULL COMMENT '세션 속성 이름.';
ALTER TABLE SPRING_SESSION_ATTRIBUTES MODIFY COLUMN ATTRIBUTE_BYTES BLOB NOT NULL COMMENT '직렬화된 세션 속성.';

ALTER TABLE user_preferences COMMENT = '사용자 음식 취향과 예산. Spring 설정 화면과 추천 context에서 사용.';
ALTER TABLE user_preferences MODIFY COLUMN user_id CHAR(36) NOT NULL COMMENT '소속 users.id.';
ALTER TABLE user_preferences MODIFY COLUMN default_budget INT NULL COMMENT '기본 예산.';
ALTER TABLE user_preferences MODIFY COLUMN spice_level VARCHAR(16) NOT NULL COMMENT '선호 매운맛 단계.';
ALTER TABLE user_preferences MODIFY COLUMN created_at DATETIME(6) NOT NULL COMMENT '취향 생성 시각.';
ALTER TABLE user_preferences MODIFY COLUMN updated_at DATETIME(6) NOT NULL COMMENT '취향 수정 시각.';
ALTER TABLE user_preferred_categories COMMENT = '사용자가 선호하는 음식 카테고리. 현재 추천 context에서 사용.';
ALTER TABLE user_preferred_categories MODIFY COLUMN user_id CHAR(36) NOT NULL COMMENT '소속 users.id.';
ALTER TABLE user_preferred_categories MODIFY COLUMN category VARCHAR(40) NOT NULL COMMENT '선호 카테고리.';
ALTER TABLE user_disliked_categories COMMENT = '사용자가 기피하는 음식 카테고리. 현재 추천 hard filter에서 사용.';
ALTER TABLE user_disliked_categories MODIFY COLUMN user_id CHAR(36) NOT NULL COMMENT '소속 users.id.';
ALTER TABLE user_disliked_categories MODIFY COLUMN category VARCHAR(40) NOT NULL COMMENT '기피 카테고리.';
ALTER TABLE user_allergies COMMENT = '사용자 알레르기 정보. 현재 추천 hard filter에서 사용.';
ALTER TABLE user_allergies MODIFY COLUMN user_id CHAR(36) NOT NULL COMMENT '소속 users.id.';
ALTER TABLE user_allergies MODIFY COLUMN allergy VARCHAR(80) NOT NULL COMMENT '알레르기 항목.';
ALTER TABLE meal_history COMMENT = '사용자가 먹은 음식점 기록. Spring history와 추천 context에서 사용.';
ALTER TABLE meal_history MODIFY COLUMN id CHAR(36) NOT NULL COMMENT '식사 기록 식별자.';
ALTER TABLE meal_history MODIFY COLUMN user_id CHAR(36) NOT NULL COMMENT '소속 users.id.';
ALTER TABLE meal_history MODIFY COLUMN restaurant_id BIGINT NOT NULL COMMENT '먹은 restaurants.id.';
ALTER TABLE meal_history MODIFY COLUMN source_message_id CHAR(36) NOT NULL COMMENT '기록을 만든 chat_messages.id.';
ALTER TABLE meal_history MODIFY COLUMN eaten_at DATETIME(6) NOT NULL COMMENT '식사 시각.';
ALTER TABLE meal_history MODIFY COLUMN created_at DATETIME(6) NOT NULL COMMENT '기록 생성 시각.';

ALTER TABLE restaurant_external_places COMMENT = '음식점과 외부 장소 후보의 매핑. Python Batch가 작성하고 Spring 추천이 참조.';
ALTER TABLE restaurant_external_places MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT COMMENT '외부 매핑 식별자.';
ALTER TABLE restaurant_external_places MODIFY COLUMN restaurant_id BIGINT NOT NULL COMMENT '소속 restaurants.id.';
ALTER TABLE restaurant_external_places MODIFY COLUMN provider VARCHAR(32) NOT NULL COMMENT '외부 제공자 구분.';
ALTER TABLE restaurant_external_places MODIFY COLUMN external_place_id VARCHAR(64) NULL COMMENT '확정된 외부 장소 식별자. NAVER_LOCAL 중간 상태에서는 NULL 가능.';
ALTER TABLE restaurant_external_places MODIFY COLUMN external_name VARCHAR(255) NULL COMMENT '외부 후보 상호.';
ALTER TABLE restaurant_external_places MODIFY COLUMN category VARCHAR(255) NULL COMMENT '외부 후보 카테고리.';
ALTER TABLE restaurant_external_places MODIFY COLUMN description VARCHAR(1000) NULL COMMENT '외부 후보 설명.';
ALTER TABLE restaurant_external_places MODIFY COLUMN link VARCHAR(1000) NULL COMMENT '외부 후보 링크.';
ALTER TABLE restaurant_external_places MODIFY COLUMN address VARCHAR(255) NULL COMMENT '외부 후보 지번 주소.';
ALTER TABLE restaurant_external_places MODIFY COLUMN road_address VARCHAR(255) NULL COMMENT '외부 후보 도로명 주소.';
ALTER TABLE restaurant_external_places MODIFY COLUMN latitude DECIMAL(10, 7) NULL COMMENT '외부 후보 위도.';
ALTER TABLE restaurant_external_places MODIFY COLUMN longitude DECIMAL(10, 7) NULL COMMENT '외부 후보 경도.';
ALTER TABLE restaurant_external_places MODIFY COLUMN match_status VARCHAR(16) NOT NULL COMMENT '외부 후보 매칭 상태.';
ALTER TABLE restaurant_external_places MODIFY COLUMN match_score DECIMAL(5, 2) NOT NULL COMMENT '후보 매칭 점수.';
ALTER TABLE restaurant_external_places MODIFY COLUMN match_distance_meters DECIMAL(10, 2) NULL COMMENT '기준점과 후보 거리.';
ALTER TABLE restaurant_external_places MODIFY COLUMN query_used VARCHAR(255) NOT NULL COMMENT '후보 조회에 사용한 검색어.';
ALTER TABLE restaurant_external_places MODIFY COLUMN matched_at DATETIME(6) NULL COMMENT '매칭 확정 시각.';
ALTER TABLE restaurant_external_places MODIFY COLUMN last_synced_at DATETIME(6) NULL COMMENT '외부 데이터 동기화 시각.';
ALTER TABLE restaurant_external_places MODIFY COLUMN created_at DATETIME(6) NOT NULL COMMENT '매핑 생성 시각.';
ALTER TABLE restaurant_external_places MODIFY COLUMN updated_at DATETIME(6) NOT NULL COMMENT '매핑 수정 시각.';
ALTER TABLE restaurant_external_places MODIFY COLUMN name_score DECIMAL(5, 2) NOT NULL DEFAULT 0.00 COMMENT '이름 비교 점수.';
ALTER TABLE restaurant_external_places MODIFY COLUMN address_score DECIMAL(5, 2) NOT NULL DEFAULT 0.00 COMMENT '주소 비교 점수.';
ALTER TABLE restaurant_external_places MODIFY COLUMN distance_score DECIMAL(5, 2) NOT NULL DEFAULT 0.00 COMMENT '거리 비교 점수.';
ALTER TABLE restaurant_external_places MODIFY COLUMN category_score DECIMAL(5, 2) NOT NULL DEFAULT 0.00 COMMENT '카테고리 비교 점수.';
ALTER TABLE restaurant_external_places MODIFY COLUMN runner_up_score DECIMAL(5, 2) NULL COMMENT '차순위 후보 점수.';
ALTER TABLE restaurant_external_places MODIFY COLUMN score_gap DECIMAL(5, 2) NULL COMMENT '최상위·차순위 점수 차이.';
ALTER TABLE restaurant_external_places MODIFY COLUMN source_content_hash VARCHAR(64) NULL COMMENT '후보 원천 내용 해시.';
ALTER TABLE restaurant_external_places MODIFY COLUMN last_attempt_status VARCHAR(16) NULL COMMENT '마지막 매칭 시도 상태.';
ALTER TABLE restaurant_external_places MODIFY COLUMN last_match_attempt_at DATETIME(6) NULL COMMENT '마지막 매칭 시도 시각.';
ALTER TABLE restaurant_external_places MODIFY COLUMN next_retry_at DATETIME(6) NULL COMMENT '다음 재시도 예정 시각.';

ALTER TABLE restaurant_menus COMMENT = 'NAVER 음식점 메뉴 상세. Python Detail Enrichment가 수집하고 Spring 추천이 참조.';
ALTER TABLE restaurant_menus MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT COMMENT '메뉴 식별자.';
ALTER TABLE restaurant_menus MODIFY COLUMN restaurant_id BIGINT NOT NULL COMMENT '소속 restaurants.id.';
ALTER TABLE restaurant_menus MODIFY COLUMN provider VARCHAR(32) NOT NULL COMMENT '상세 제공자 구분.';
ALTER TABLE restaurant_menus MODIFY COLUMN external_place_id VARCHAR(64) NOT NULL COMMENT '외부 장소 식별자.';
ALTER TABLE restaurant_menus MODIFY COLUMN external_menu_id VARCHAR(128) NOT NULL COMMENT '외부 메뉴 식별자.';
ALTER TABLE restaurant_menus MODIFY COLUMN name VARCHAR(255) NOT NULL COMMENT '메뉴 이름.';
ALTER TABLE restaurant_menus MODIFY COLUMN description TEXT NULL COMMENT '메뉴 설명.';
ALTER TABLE restaurant_menus MODIFY COLUMN price_value INT NULL COMMENT '숫자로 변환된 메뉴 가격.';
ALTER TABLE restaurant_menus MODIFY COLUMN price_text VARCHAR(255) NULL COMMENT '원문 가격 표시.';
ALTER TABLE restaurant_menus MODIFY COLUMN price_type VARCHAR(64) NULL COMMENT '가격 유형.';
ALTER TABLE restaurant_menus MODIFY COLUMN menu_type VARCHAR(64) NULL COMMENT '메뉴 유형.';
ALTER TABLE restaurant_menus MODIFY COLUMN is_set_menu BOOLEAN NULL COMMENT '세트 메뉴 여부.';
ALTER TABLE restaurant_menus MODIFY COLUMN thumbnail_url VARCHAR(1000) NULL COMMENT '메뉴 썸네일 주소.';
ALTER TABLE restaurant_menus MODIFY COLUMN active BOOLEAN NOT NULL DEFAULT TRUE COMMENT '현재 유효한 메뉴 여부.';
ALTER TABLE restaurant_menus MODIFY COLUMN source_updated_at DATETIME(6) NULL COMMENT '외부 원천 수정 시각.';
ALTER TABLE restaurant_menus MODIFY COLUMN crawled_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '수집 시각.';

ALTER TABLE restaurant_business_hours COMMENT = 'NAVER 음식점 영업시간 상세. Python Detail Enrichment가 수집.';
ALTER TABLE restaurant_business_hours MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT COMMENT '영업시간 상세 식별자.';
ALTER TABLE restaurant_business_hours MODIFY COLUMN restaurant_id BIGINT NOT NULL COMMENT '소속 restaurants.id.';
ALTER TABLE restaurant_business_hours MODIFY COLUMN provider VARCHAR(32) NOT NULL COMMENT '상세 제공자 구분.';
ALTER TABLE restaurant_business_hours MODIFY COLUMN external_place_id VARCHAR(64) NOT NULL COMMENT '외부 장소 식별자.';
ALTER TABLE restaurant_business_hours MODIFY COLUMN day_of_week VARCHAR(32) NOT NULL COMMENT '요일 또는 영업 구간.';
ALTER TABLE restaurant_business_hours MODIFY COLUMN open_time VARCHAR(32) NULL COMMENT '영업 시작 표시.';
ALTER TABLE restaurant_business_hours MODIFY COLUMN close_time VARCHAR(32) NULL COMMENT '영업 종료 표시.';
ALTER TABLE restaurant_business_hours MODIFY COLUMN break_hours VARCHAR(255) NULL COMMENT '휴게시간 표시.';
ALTER TABLE restaurant_business_hours MODIFY COLUMN last_order VARCHAR(255) NULL COMMENT '라스트오더 표시.';
ALTER TABLE restaurant_business_hours MODIFY COLUMN description VARCHAR(1000) NULL COMMENT '영업시간 설명.';
ALTER TABLE restaurant_business_hours MODIFY COLUMN regular_closed_day VARCHAR(255) NULL COMMENT '정기 휴무 표시.';
ALTER TABLE restaurant_business_hours MODIFY COLUMN irregular_closed_day VARCHAR(255) NULL COMMENT '비정기 휴무 표시.';
ALTER TABLE restaurant_business_hours MODIFY COLUMN business_status VARCHAR(255) NULL COMMENT '영업 상태 표시.';
ALTER TABLE restaurant_business_hours MODIFY COLUMN crawled_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '수집 시각.';

ALTER TABLE restaurant_review_summaries COMMENT = 'NAVER 방문자·블로그 리뷰 요약. Python Detail Enrichment가 수집.';
ALTER TABLE restaurant_review_summaries MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT COMMENT '리뷰 요약 식별자.';
ALTER TABLE restaurant_review_summaries MODIFY COLUMN restaurant_id BIGINT NOT NULL COMMENT '소속 restaurants.id.';
ALTER TABLE restaurant_review_summaries MODIFY COLUMN provider VARCHAR(32) NOT NULL COMMENT '리뷰 제공자 구분.';
ALTER TABLE restaurant_review_summaries MODIFY COLUMN external_place_id VARCHAR(64) NOT NULL COMMENT '외부 장소 식별자.';
ALTER TABLE restaurant_review_summaries MODIFY COLUMN visitor_reviews_total INT NULL COMMENT '방문자 리뷰 총수.';
ALTER TABLE restaurant_review_summaries MODIFY COLUMN visitor_reviews_score DECIMAL(4, 2) NULL COMMENT '방문자 리뷰 평점.';
ALTER TABLE restaurant_review_summaries MODIFY COLUMN visitor_text_review_total INT NULL COMMENT '방문자 텍스트 리뷰 수.';
ALTER TABLE restaurant_review_summaries MODIFY COLUMN cafe_blog_reviews_total INT NULL COMMENT '블로그 리뷰 수.';
ALTER TABLE restaurant_review_summaries MODIFY COLUMN crawled_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '수집 시각.';

ALTER TABLE restaurant_review_keywords COMMENT = 'NAVER 리뷰 키워드 집계. Python Detail Enrichment가 수집.';
ALTER TABLE restaurant_review_keywords MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT COMMENT '키워드 식별자.';
ALTER TABLE restaurant_review_keywords MODIFY COLUMN restaurant_id BIGINT NOT NULL COMMENT '소속 restaurants.id.';
ALTER TABLE restaurant_review_keywords MODIFY COLUMN provider VARCHAR(32) NOT NULL COMMENT '리뷰 제공자 구분.';
ALTER TABLE restaurant_review_keywords MODIFY COLUMN external_place_id VARCHAR(64) NOT NULL COMMENT '외부 장소 식별자.';
ALTER TABLE restaurant_review_keywords MODIFY COLUMN keyword_kind VARCHAR(32) NOT NULL COMMENT '키워드 종류.';
ALTER TABLE restaurant_review_keywords MODIFY COLUMN keyword VARCHAR(255) NOT NULL COMMENT '리뷰 키워드.';
ALTER TABLE restaurant_review_keywords MODIFY COLUMN mention_count INT NULL COMMENT '키워드 언급 횟수.';
ALTER TABLE restaurant_review_keywords MODIFY COLUMN crawled_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '수집 시각.';

ALTER TABLE restaurant_representative_reviews COMMENT = '대표 NAVER 리뷰 원문. Python Detail Enrichment가 수집.';
ALTER TABLE restaurant_representative_reviews MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT COMMENT '대표 리뷰 식별자.';
ALTER TABLE restaurant_representative_reviews MODIFY COLUMN restaurant_id BIGINT NOT NULL COMMENT '소속 restaurants.id.';
ALTER TABLE restaurant_representative_reviews MODIFY COLUMN provider VARCHAR(32) NOT NULL COMMENT '리뷰 제공자 구분.';
ALTER TABLE restaurant_representative_reviews MODIFY COLUMN external_place_id VARCHAR(64) NOT NULL COMMENT '외부 장소 식별자.';
ALTER TABLE restaurant_representative_reviews MODIFY COLUMN review_id VARCHAR(128) NOT NULL COMMENT '외부 리뷰 식별자.';
ALTER TABLE restaurant_representative_reviews MODIFY COLUMN review_text TEXT NOT NULL COMMENT '리뷰 원문.';
ALTER TABLE restaurant_representative_reviews MODIFY COLUMN review_date VARCHAR(64) NULL COMMENT '리뷰 작성일 표시.';
ALTER TABLE restaurant_representative_reviews MODIFY COLUMN rating DECIMAL(4, 2) NULL COMMENT '리뷰 평점.';
ALTER TABLE restaurant_representative_reviews MODIFY COLUMN crawled_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '수집 시각.';

ALTER TABLE restaurant_naver_verifications COMMENT = 'KOMSCO 음식점의 NAVER Entity Resolution 결과. Python Batch가 현재 사용.';
ALTER TABLE restaurant_naver_verifications MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT COMMENT '검증 결과 식별자.';
ALTER TABLE restaurant_naver_verifications MODIFY COLUMN restaurant_id BIGINT NOT NULL COMMENT '검증 대상 restaurants.id.';
ALTER TABLE restaurant_naver_verifications MODIFY COLUMN provider VARCHAR(32) NOT NULL COMMENT '검증 제공자 구분.';
ALTER TABLE restaurant_naver_verifications MODIFY COLUMN verification_status VARCHAR(16) NOT NULL COMMENT 'VERIFIED/REJECTED/ERROR 등 검증 상태.';
ALTER TABLE restaurant_naver_verifications MODIFY COLUMN verification_reason VARCHAR(64) NOT NULL COMMENT '검증 상태의 세부 사유.';
ALTER TABLE restaurant_naver_verifications MODIFY COLUMN source_fingerprint VARCHAR(64) NULL COMMENT 'KOMSCO 원천 변경 감지용 fingerprint.';
ALTER TABLE restaurant_naver_verifications MODIFY COLUMN external_place_id VARCHAR(64) NULL COMMENT '검증된 외부 장소 식별자.';
ALTER TABLE restaurant_naver_verifications MODIFY COLUMN model_name VARCHAR(128) NULL COMMENT '검증에 사용한 모델 이름.';
ALTER TABLE restaurant_naver_verifications MODIFY COLUMN verified_at DATETIME(6) NULL COMMENT '검증 확정 시각.';
ALTER TABLE restaurant_naver_verifications MODIFY COLUMN last_attempt_at DATETIME(6) NOT NULL COMMENT '마지막 검증 시도 시각.';

ALTER TABLE canonical_restaurants COMMENT = '검증된 음식점의 정규화된 대표 정보. ACCEPT 결과만 Python Batch가 생성.';
ALTER TABLE canonical_restaurants MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT COMMENT 'Canonical 식별자.';
ALTER TABLE canonical_restaurants MODIFY COLUMN restaurant_id BIGINT NOT NULL COMMENT '원본 restaurants.id.';
ALTER TABLE canonical_restaurants MODIFY COLUMN name VARCHAR(120) NOT NULL COMMENT '정규화된 음식점 이름.';
ALTER TABLE canonical_restaurants MODIFY COLUMN category VARCHAR(255) NULL COMMENT '정규화된 카테고리.';
ALTER TABLE canonical_restaurants MODIFY COLUMN address VARCHAR(255) NOT NULL COMMENT '정규화된 주소.';
ALTER TABLE canonical_restaurants MODIFY COLUMN road_address VARCHAR(255) NULL COMMENT '정규화된 도로명 주소.';
ALTER TABLE canonical_restaurants MODIFY COLUMN latitude DECIMAL(10, 7) NULL COMMENT '정규화된 위도.';
ALTER TABLE canonical_restaurants MODIFY COLUMN longitude DECIMAL(10, 7) NULL COMMENT '정규화된 경도.';
ALTER TABLE canonical_restaurants MODIFY COLUMN created_at DATETIME(6) NOT NULL COMMENT 'Canonical 생성 시각.';
ALTER TABLE canonical_restaurants MODIFY COLUMN updated_at DATETIME(6) NOT NULL COMMENT 'Canonical 수정 시각.';

ALTER TABLE subway_stations COMMENT = '강남구 지하철역 기준 위치 데이터. Spring 위치 기능에서 사용.';
ALTER TABLE subway_stations MODIFY COLUMN id VARCHAR(32) NOT NULL COMMENT '역 식별자.';
ALTER TABLE subway_stations MODIFY COLUMN name VARCHAR(255) NOT NULL COMMENT '역 이름.';
ALTER TABLE subway_stations MODIFY COLUMN line VARCHAR(100) NULL COMMENT '노선 정보.';
ALTER TABLE subway_stations MODIFY COLUMN latitude DECIMAL(10, 7) NOT NULL COMMENT '역 위도.';
ALTER TABLE subway_stations MODIFY COLUMN longitude DECIMAL(10, 7) NOT NULL COMMENT '역 경도.';
ALTER TABLE subway_stations MODIFY COLUMN active BOOLEAN NOT NULL COMMENT '활성 역 여부.';
ALTER TABLE subway_stations MODIFY COLUMN source VARCHAR(255) NULL COMMENT '역 데이터 출처.';
ALTER TABLE subway_stations MODIFY COLUMN source_updated_at TIMESTAMP NULL COMMENT '출처 데이터 수정 시각.';

ALTER TABLE shedlock COMMENT = '스케줄러 중복 실행 방지용 ShedLock 저장소. Spring scheduler에서 사용.';
ALTER TABLE shedlock MODIFY COLUMN name VARCHAR(64) NOT NULL COMMENT '잠금 이름.';
ALTER TABLE shedlock MODIFY COLUMN lock_until TIMESTAMP(3) NOT NULL COMMENT '잠금 만료 시각.';
ALTER TABLE shedlock MODIFY COLUMN locked_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '잠금 획득 시각.';
ALTER TABLE shedlock MODIFY COLUMN locked_by VARCHAR(255) NOT NULL COMMENT '잠금을 획득한 실행 인스턴스.';
